# Generated by Django 4.2.1 on 2024-04-13 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='msgchat',
            name='status',
            field=models.CharField(choices=[('read', 'Read'), ('unread', 'Unread')], default='unread', max_length=20),
        ),
    ]
