# Generated by Django 4.2.1 on 2024-04-12 09:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_msgroom_alter_msgchat_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='msgchat',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='MsgRoom',
        ),
    ]
